version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: cipherstudio-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cipherstudio
    networks:
      - cipherstudio-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cipherstudio-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/cipherstudio
      - PORT=5000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - cipherstudio-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cipherstudio-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - cipherstudio-network

volumes:
  mongodb_data:

networks:
  cipherstudio-network:
    driver: bridge

